In [1]:
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from itertools import permutations
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori 
from mlxtend.frequent_patterns import association_rules
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv("Megastore_Dataset_Task_3 3.csv")
df

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,OrderPriority,Region,Segment,ExpeditedShipping,PaymentMethod,CustomerOrderSatisfaction
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8229,580263,DANISH ROSE DELUXE COASTER,12,12/2/11 12:43,$0.85,$10.20,United States,No,High,Southeast,Corporate,Yes,PayPal,Dissatisfied
8230,580263,CACTI TLIGHT CANDLES,16,12/2/11 12:43,$0.42,$6.72,United States,No,High,Southeast,Corporate,Yes,PayPal,Dissatisfied
8231,581316,RED RETROSPOT SUGAR JAM BOWL,1,12/8/11 11:46,$2.55,$2.55,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied
8232,581316,GLASS SONGBIRD STORAGE JAR,1,12/8/11 11:46,$12.50,$12.50,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied
8233,581316,REGENCY SUGAR BOWL GREEN,1,12/8/11 11:46,$4.15,$4.15,United States,No,High,Southeast,Consumer,No,Credit Card,Very Satisfied

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderID                    8234 non-null   int64
 1   ProductName                8234 non-null   object
 2   Quantity                   8234 non-null   int64
 3   InvoiceDate                8234 non-null   object
 4   UnitPrice                  8234 non-null   object
 5   TotalCost                  8234 non-null   object
 6   Country                    8234 non-null   object
 7   DiscountApplied            8234 non-null   object
 8   OrderPriority              8234 non-null   object
 9   Region                     8234 non-null   object
 10  Segment                    8234 non-null   object
 11  ExpeditedShipping          8234 non-null   object
 12  PaymentMethod              8234 non-null   object
 13  CustomerOrderSatisfaction  8234 non-null   object
dtypes: int64(2), object(12)
memory usage: 900.7+ KB

In [7]:
df.isnull().any()

OrderID                      False
ProductName                  False
Quantity                     False
InvoiceDate                  False
UnitPrice                    False
TotalCost                    False
Country                      False
DiscountApplied              False
OrderPriority                False
Region                       False
Segment                      False
ExpeditedShipping            False
PaymentMethod                False
CustomerOrderSatisfaction    False
dtype: bool

In [9]:
df.isna().any()

OrderID                      False
ProductName                  False
Quantity                     False
InvoiceDate                  False
UnitPrice                    False
TotalCost                    False
Country                      False
DiscountApplied              False
OrderPriority                False
Region                       False
Segment                      False
ExpeditedShipping            False
PaymentMethod                False
CustomerOrderSatisfaction    False
dtype: bool

In [11]:
df.describe()

             OrderID     Quantity
count    8234.000000  8234.000000
mean   560874.506923    13.705125
std     13082.500625    21.494536
min    536370.000000     1.000000
25%    549274.000000     6.000000
50%    563502.000000    10.000000
75%    571864.000000    12.000000
max    581587.000000   912.000000

In [13]:
df.nunique()

OrderID                       441
ProductName                  1562
Quantity                       57
InvoiceDate                   441
UnitPrice                      86
TotalCost                     443
Country                         1
DiscountApplied                 2
OrderPriority                   2
Region                          2
Segment                         2
ExpeditedShipping               2
PaymentMethod                   2
CustomerOrderSatisfaction       5
dtype: int64

In [15]:
unique1 = df['CustomerOrderSatisfaction'].unique()
print("Unique values using unique():", unique1)

Unique values using unique(): ['Satisfied' 'Dissatisfied' 'Prefer not to answer' 'Very Satisfied'
 'Very Dissatisfied']

In [17]:
df.head()

,OrderID,ProductName,Quantity,InvoiceDate,UnitPrice,TotalCost,Country,DiscountApplied,OrderPriority,Region,Segment,ExpeditedShipping,PaymentMethod,CustomerOrderSatisfaction
0,536370,INFLATABLE POLITICAL GLOBE,48,12/1/10 8:45,$0.85,$40.80,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
1,536370,SET2 RED RETROSPOT TEA TOWELS,18,12/1/10 8:45,$2.95,$53.10,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
2,536370,PANDA AND BUNNIES STICKER SHEET,12,12/1/10 8:45,$0.85,$10.20,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
3,536370,RED TOADSTOOL LED NIGHT LIGHT,24,12/1/10 8:45,$1.65,$39.60,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied
4,536370,VINTAGE HEADS AND TAILS CARD GAME,24,12/1/10 8:45,$1.25,$30.00,United States,Yes,High,Northeast,Corporate,Yes,Credit Card,Satisfied

In [19]:
order1 = df['OrderID'].value_counts().idxmax()
transaction1 = df[df['OrderID'] == order1][['OrderID', 'ProductName', 'Quantity']]
print(transaction1.head(10))

      OrderID                       ProductName  Quantity
5731   570672              RED RETROSPOT PURSE          6
5732   570672               GREEN POLKADOT BOWL        16
5733   570672                BLUE POLKADOT BOWL         8
5734   570672                RED RETROSPOT BOWL         8
5735   570672                PINK POLKADOT BOWL         8
5736   570672  RED RETROSPOT CHILDRENS UMBRELLA         6
5737   570672                 MR ROBOT SOFT TOY         2
5738   570672            STRAWBERRY SHOPPER BAG        10
5739   570672         RED RETROSPOT SHOPPER BAG        10
5740   570672            WOODLAND CHARLOTTE BAG        10

In [21]:
transactions = df.groupby('OrderID')['ProductName'].apply(list).values.tolist()
transactions

[['INFLATABLE POLITICAL GLOBE ',
  'SET2 RED RETROSPOT TEA TOWELS ',
  'PANDA AND BUNNIES STICKER SHEET',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'VINTAGE HEADS AND TAILS CARD GAME ',
  'STARS GIFT TAPE ',
  'VINTAGE SEASIDE JIGSAW PUZZLES',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'MINI PAINT SET VINTAGE ',
  'MINI JIGSAW CIRCUS PARADE ',
  'MINI JIGSAW SPACEBOY',
  'SPACEBOY LUNCH BOX ',
  'CIRCUS PARADE LUNCH BOX ',
  'LUNCH BOX I LOVE LONDON',
  'CHARLOTTE BAG DOLLY GIRL DESIGN',
  'ALARM CLOCK BAKELIKE GREEN',
  'ALARM CLOCK BAKELIKE RED ',
  'ALARM CLOCK BAKELIKE PINK',
  'SET 2 TEA TOWELS I LOVE LONDON '],
 ['POLKADOT RAIN HAT ',
  'VINTAGE HEADS AND TAILS CARD GAME ',
  'MINI JIGSAW DOLLY GIRL',
  'MINI JIGSAW SPACEBOY',
  'PICTURE DOMINOES',
  'CHARLOTTE BAG DOLLY GIRL DESIGN'],
 ['EDWARDIAN PARASOL RED',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'ASSORTED COLOUR MINI CASES',
  'RED RETROSPOT MINI CASES',
  'BIG DOUGHNUT FRIDGE MAGNETS',
  'RED  HARMONICA IN BOX ',
  'TEA PARTY BIRTHDAY CARD',
  'RIBBON REEL POLKADOTS ',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'LUNCH BOX I LOVE LONDON',
  'POPPYS PLAYHOUSE KITCHEN',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'EDWARDIAN PARASOL BLACK',
  'EDWARDIAN PARASOL PINK'],
 ['PARTY TIME PENCIL ERASERS',
  'RED RETROSPOT PURSE ',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG CARS BLUE',
  'ASSORTED COLOUR MINI CASES',
  'RED RETROSPOT MINI CASES',
  'NURSES BAG SOFT TOY',
  'TOOL BOX SOFT TOY ',
  'SET10 RED POLKADOT PARTY CANDLES',
  'PINK  HONEYCOMB PAPER BALL ',
  'BASKET OF TOADSTOOLS',
  'RETROSPOT LARGE MILK JUG',
  'RED RETROSPOT BUTTER DISH',
  'CERAMIC STRAWBERRY TRINKET TRAY',
  'CERAMIC STRAWBERRY MONEY BOX',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'DECORATIVE CATS BATHROOM BOTTLE',
  'POLKADOT RAIN HAT ',
  'RAIN PONCHO RETROSPOT',
  'DINOSAUR KEYRINGS ASSORTED',
  'TRADITIONAL WOODEN CATCH CUP GAME ',
  'PACK OF 12 RED RETROSPOT TISSUES ',
  'PACK OF 12 WOODLAND TISSUES ',
  'PACK OF 12 SUKI TISSUES ',
  'RETROSPOT LAMP',
  '5 HOOK HANGER RED MAGIC TOADSTOOL',
  'FIVE HEART HANGING DECORATION',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'PAPERWEIGHT CHILDHOOD MEMORIES',
  'REGENCY CAKESTAND 3 TIER',
  'GUMBALL COAT RACK',
  'RED GINGHAM TEDDY BEAR ',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PACK OF 12 SPACEBOY TISSUES',
  'PACK OF 12 CIRCUS PARADE TISSUES ',
  'SET OF 6 SOLDIER SKITTLES',
  'HAND WARMER RED RETROSPOT',
  'CHILDS BREAKFAST SET SPACEBOY ',
  'CHILDS BREAKFAST SET DOLLY GIRL ',
  'CHILDS BREAKFAST SET CIRCUS PARADE',
  'CERAMIC CHERRY CAKE MONEY BANK',
  'ALARM CLOCK BAKELIKE GREEN',
  'ALARM CLOCK BAKELIKE RED ',
  'ALARM CLOCK BAKELIKE PINK',
  'ALARM CLOCK BAKELIKE ORANGE',
  'HOT WATER BOTTLE BABUSHKA ',
  'BREAD BIN DINER STYLE RED ',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'ROSE COTTAGE KEEPSAKE BOX ',
  'PARTY BUNTING',
  'CLASSICAL ROSE SMALL VASE',
  'SET OF 6 3D KIT CARDS FOR KIDS',
  'CHERRY BLOSSOM  DECORATIVE FLASK',
  'BLUE GEISHA GIRL ',
  'GREEN GEISHA GIRL ',
  'PINK PAINTED KASHMIRI CHAIR',
  'GREEN 3 PIECE POLKADOT CUTLERY SET',
  'RED 3 PIECE RETROSPOT CUTLERY SET',
  'BLUE 3 PIECE POLKADOT CUTLERY SET'],
 ['PINK POLKADOT CHILDRENS UMBRELLA',
  'RED RETROSPOT CHILDRENS UMBRELLA',
  'WOODLAND CHARLOTTE BAG',
  'BOOM BOX SPEAKER BOYS',
  'SET10 RED POLKADOT PARTY CANDLES',
  'SET10 BLUE POLKADOT PARTY CANDLES',
  'BLACK RECORD COVER FRAME',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'SET4 SKULL BADGES',
  'RED RETROSPOT CUP',
  'FANCY FONT BIRTHDAY CARD, ',
  'SKULLS  WATER TRANSFER TATTOOS ',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'WOODLAND  STICKERS',
  'BIG DOUGHNUT FRIDGE MAGNETS',
  'LOVELY BONBON STICKER SHEET',
  'CANDY SHOP  STICKER SHEET',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'TEA PARTY BIRTHDAY CARD',
  'ROBOT BIRTHDAY CARD',
  'RECORD FRAME 7 SINGLE SIZE ',
  'SNOWSTORM PHOTO FRAME FRIDGE MAGNET',
  'IVORY DINER WALL CLOCK',
  'COFFEE MUG DOG  BALL DESIGN',
  'COFFEE MUG CAT  BIRD DESIGN',
  'OFFICE MUG WARMER POLKADOT',
  'OFFICE MUG WARMER PINK',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'TEA BAG PLATE RED RETROSPOT',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'DOORMAT RESPECTABLE HOUSE',
  'METAL SIGN TAKE IT OR LEAVE IT ',
  'GUMBALL COAT RACK',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'TABLECLOTH RED APPLES DESIGN ',
  'SET OF 2 TEA TOWELS APPLE AND PEARS',
  'PACK OF 20 NAPKINS RED APPLES',
  'JAM MAKING SET PRINTED',
  'BOX OF 24 COCKTAIL PARASOLS'],
 ['LUNCH BAG RED RETROSPOT',
  'RETROSPOT HEART HOT WATER BOTTLE',
  'BIRD HOUSE HOT WATER BOTTLE',
  'SCOTTIE DOG HOT WATER BOTTLE',
  'GREY HEART HOT WATER BOTTLE',
  'HOT WATER BOTTLE TEA AND SYMPATHY',
  'FELTCRAFT DOLL MARIA',
  'LUNCH BAG SPACEBOY DESIGN ',
  'LUNCH BAG SUKI  DESIGN ',
  '10 COLOUR SPACEBOY PEN',
  'MAGIC DRAWING SLATE CIRCUS PARADE  ',
  'CLOTHES PEGS RETROSPOT PACK 24 ',
  'DELUXE SEWING KIT ',
  'POPPYS PLAYHOUSE BEDROOM ',
  'POPPYS PLAYHOUSE BATHROOM',
  'POPPYS PLAYHOUSE KITCHEN',
  'FELTCRAFT PRINCESS CHARLOTTE DOLL',
  'FELTCRAFT PRINCESS LOLA DOLL',
  'HOT WATER BOTTLE BABUSHKA '],
 ['BLUE SCANDINAVIAN PAISLEY WRAP',
  'VINTAGE CARAVAN GIFT WRAP',
  'PAPER CHAIN KIT 50S CHRISTMAS ',
  'WRAP I LOVE LONDON ',
  'MAKE YOUR OWN PLAYTIME CARD KIT',
  'MAKE YOUR OWN MONSOON CARD KIT',
  'PAPER CHAIN KIT VINTAGE CHRISTMAS',
  'FAIRY CAKE BIRTHDAY CANDLE SET',
  'TEA TIME PARTY BUNTING',
  'TRADITIONAL CHRISTMAS RIBBONS'],
 ['SILK PURSE BABUSHKA BLUE',
  'DOLLY GIRL LUNCH BOX',
  'CHILDS BREAKFAST SET SPACEBOY '],
 ['DOORMAT RED RETROSPOT',
  'FAWN BLUE HOT WATER BOTTLE',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'FELT TOADSTOOL  SMALL',
  'MEASURING TAPE BABUSHKA RED',
  'SET OF 2 ROUND TINS CAMEMBERT ',
  'CLOTHES PEGS RETROSPOT PACK 24 ',
  'CHRISTMAS RETROSPOT ANGEL WOOD',
  'CHARLOTTE BAG DOLLY GIRL DESIGN',
  'SET 7 BABUSHKA NESTING BOXES',
  'CHILDRENS DOLLY GIRL MUG',
  'RED WOOLLY HOTTIE WHITE HEART.'],
 ['RED RETROSPOT CAKE STAND', 'RECIPE BOX RETROSPOT '],
 ['PINK CREAM FELT CRAFT TRINKET BOX ',
  'SET6 RED SPOTTY PAPER CUPS',
  'SET6 RED SPOTTY PAPER PLATES',
  'SET10 RED POLKADOT PARTY CANDLES',
  'SET10 PINK POLKADOT PARTY CANDLES',
  'SET10 IVORY POLKADOT PARTY CANDLES',
  'SET10 BLUE POLKADOT PARTY CANDLES',
  'RED RETROSPOT OVEN GLOVE ',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'RED RETROSPOT CAKE STAND',
  'WOODLAND PARTY BAG  STICKER SET',
  'RETROSPOT PARTY BAG  STICKER SET',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'SET OF 9 HEART SHAPED BALLOONS',
  'SET OF 9 BLACK SKULL BALLOONS',
  'DOLLY GIRL LUNCH BOX',
  'CHILDS BREAKFAST SET CIRCUS PARADE',
  'WRAP RED APPLES ',
  'WRAP GREEN PEARS ',
  'EASTER TIN BUNNY BOUQUET',
  'TABLECLOTH RED APPLES DESIGN ',
  'SET OF 2 TEA TOWELS APPLE AND PEARS',
  'OVEN MITT APPLES DESIGN',
  'CHILDRENS APRON APPLES DESIGN',
  'CHILDRENS APRON DOLLY GIRL ',
  'PACK OF 20 NAPKINS PANTRY DESIGN',
  'PACK OF 20 NAPKINS RED APPLES',
  'SET OF 20 VINTAGE CHRISTMAS NAPKINS',
  'CUPCAKE LACE PAPER SET 6',
  '60 CAKE CASES DOLLY GIRL DESIGN',
  'CHILDRENS SPACEBOY MUG',
  'CHILDRENS CIRCUS PARADE MUG',
  'CHILDRENS DOLLY GIRL MUG',
  'SPACEBOY CHILDRENS EGG CUP',
  'CIRCUS PARADE CHILDRENS EGG CUP ',
  'DOLLY GIRL CHILDRENS EGG CUP',
  '72 SWEETHEART FAIRY CAKE CASES',
  'PINK PARTY BAGS',
  'BLUE PARTY BAGS ',
  'PINK 3 PIECE POLKADOT CUTLERY SET'],
 ['INFLATABLE POLITICAL GLOBE ',
  'EDWARDIAN PARASOL RED',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'ASSORTED COLOUR MINI CASES',
  'RED RETROSPOT MINI CASES',
  'TOADSTOOL MONEY BOX',
  'SKULL LUNCH BOX WITH CUTLERY ',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'BIG DOUGHNUT FRIDGE MAGNETS',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'VINTAGE HEADS AND TAILS CARD GAME ',
  '6 RIBBONS RUSTIC CHARM',
  'RIBBON REEL STRIPES DESIGN ',
  'SMALL POPCORN HOLDER',
  'HAIRCLIPS FORTIES FABRIC ASSORTED',
  'BIRD DECORATION RED RETROSPOT',
  'LUNCH BAG SPACEBOY DESIGN ',
  'LUNCH BAG SUKI  DESIGN ',
  'JUMBO BAG SPACEBOY DESIGN',
  'JUMBO BAG PINK POLKADOT',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PLASTERS IN TIN CIRCUS PARADE ',
  '4 TRADITIONAL SPINNING TOPS',
  'RIBBON REEL MAKING SNOWMEN ',
  'RIBBON REEL SNOWY VILLAGE',
  'SET OF 20 VINTAGE CHRISTMAS NAPKINS',
  'METAL DECORATION NAUGHTY CHILDREN ',
  'JAM MAKING SET PRINTED',
  'EDWARDIAN PARASOL BLACK',
  'SET3 DECOUPAGE STACKING TINS'],
 ['INFLATABLE POLITICAL GLOBE ',
  'RED RETROSPOT CHILDRENS UMBRELLA',
  'DOORMAT RED RETROSPOT',
  'LUNCH BAG RED RETROSPOT',
  'ELEPHANT, BIRTHDAY CARD, ',
  'RED RETROSPOT TRADITIONAL TEAPOT ',
  'RETROSPOT LARGE MILK JUG',
  'WOODEN BOX OF DOMINOES',
  'BLUE HARMONICA IN BOX ',
  'RED  HARMONICA IN BOX ',
  'PICTURE DOMINOES',
  'CLOTHES PEGS RETROSPOT PACK 24 ',
  'TRADITIONAL MODELLING CLAY',
  'DOORMAT UNION FLAG',
  'ASSORTED COLOUR BIRD ORNAMENT'],
 ['FUNKY WASHING UP GLOVES ASSORTED',
  'STRAWBERRY BATH SPONGE ',
  'SANDWICH BATH SPONGE',
  'GREY FLORAL FELTCRAFT SHOULDER BAG',
  'PINK CREAM FELT CRAFT TRINKET BOX ',
  '12 PENCILS TALL TUBE RED RETROSPOT',
  'ANTIQUE ALL GLASS CANDLESTICK',
  'SPACE OWL',
  'NINJA RABBIT PINK',
  'SPACE CADET RED',
  'REX CASHCARRY JUMBO SHOPPER',
  'VINTAGE BILLBOARD TEA MUG',
  'KEEP OUT BOYS DOOR HANGER ',
  'ETCHED GLASS COASTER',
  'AGED GLASS SILVER TLIGHT HOLDER',
  'BALLOONS  WRITING SET ',
  'LETS GO SHOPPING COTTON TOTE BAG',
  'WOODLAND DESIGN  COTTON TOTE BAG',
  'KEY FOB , SHED',
  'KEY FOB , BACK DOOR ',
  'PACK OF 12 RED RETROSPOT TISSUES ',
  'PACK OF 12 WOODLAND TISSUES ',
  'PACK OF 12 SUKI TISSUES ',
  'PACK OF 12 HEARTS DESIGN TISSUES ',
  'PACK OF 12 PINK POLKADOT TISSUES',
  '6 RIBBONS EMPIRE  ',
  'RIBBON REEL LACE DESIGN ',
  'RIBBON REEL HEARTS DESIGN ',
  'RIBBON REEL STRIPES DESIGN ',
  'MOTORING TISSUE BOX',
  'RED RETROSPOT TISSUE BOX',
  'PLACE SETTING WHITE HEART',
  'PHOTO CUBE',
  'AIRLINE BAG VINTAGE JET SET RED',
  'AIRLINE BAG VINTAGE JET SET BROWN',
  'MAGNETS PACK OF 4 CHILDHOOD MEMORY',
  'MAGNETS PACK OF 4 VINTAGE COLLAGE',
  'MAGNETS PACK OF 4 VINTAGE LABELS ',
  'METAL SIGN TAKE IT OR LEAVE IT ',
  'SET OF 9 HEART SHAPED BALLOONS',
  'HEART OF WICKER SMALL',
  'RED TEA TOWEL CLASSIC DESIGN',
  'BLUE TEA TOWEL CLASSIC DESIGN',
  'SET OF 4 NAPKIN CHARMS CUTLERY',
  'CIRCUS PARADE LUNCH BOX ',
  'SET OF 4 NAPKIN CHARMS CROWNS ',
  'WICKER WREATH LARGE',
  'SET OF 3 CAKE TINS PANTRY DESIGN ',
  'RIBBON REEL CHRISTMAS SOCK BAUBLE',
  'FELTCRAFT PRINCESS CHARLOTTE DOLL',
  'SET OF 3 NOTEBOOKS IN PARCEL',
  'SQUARECUSHION COVER PINK UNION FLAG',
  'ANTIQUE GLASS PEDESTAL BOWL',
  'SET OF 20 VINTAGE CHRISTMAS NAPKINS',
  'PAPER CHAIN KIT VINTAGE CHRISTMAS',
  'FELTCRAFT CHRISTMAS FAIRY',
  'CHRISTMAS METAL TAGS ASSORTED ',
  'SET OF 3 HEART COOKIE CUTTERS',
  'S6 SEW ON CROCHET FLOWERS',
  'ASSTD DESIGN 3D PAPER STICKERS',
  'ZINC METAL HEART DECORATION',
  'ANTIQUE SILVER TEA GLASS ENGRAVED',
  'BLACK CANDELABRA TLIGHT HOLDER',
  'CAROUSEL DESIGN WASHBAG',
  'SCOTTIES DESIGN WASHBAG',
  'SCANDINAVIAN REDS RIBBONS',
  'URBAN BLACK RIBBONS '],
 ['LUNCH BAG DOLLY GIRL DESIGN'],
 ['LUNCH BAG DOLLY GIRL DESIGN'],
 ['RECIPE BOX RETROSPOT '],
 ['BLUE HARMONICA IN BOX ',
  'FELT TOADSTOOL  SMALL',
  'FELT FARM ANIMAL WHITE BUNNY ',
  'RETROSPOT PARTY BAG  STICKER SET',
  'MINI PAINT SET VINTAGE '],
 ['RED RETROSPOT MINI CASES',
  'TOADSTOOL MONEY BOX',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'ROUND SNACK BOXES SET OF4 WOODLAND '],
 ['PINK POLKADOT CHILDRENS UMBRELLA',
  'RED RETROSPOT CHILDRENS UMBRELLA',
  'LUNCH BAG WOODLAND',
  'TOAST ITS  I LOVE YOU ',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'WOODLAND PARTY BAG  STICKER SET',
  'RETROSPOT PARTY BAG  STICKER SET',
  'FAIRY TALE COTTAGE NIGHTLIGHT',
  'HAND WARMER BABUSHKA DESIGN',
  'PINK HEART SHAPE EGG FRYING PAN',
  'ASS COLOUR GLOWING TIARAS',
  'EDWARDIAN PARASOL NATURAL',
  'EDWARDIAN PARASOL PINK',
  'RED DRAGONFLY HELICOPTER'],
 ['FIRST CLASS PASSPORT COVER ',
  'RED RETROSPOT MINI CASES',
  'BOOM BOX SPEAKER GIRLS',
  'SET20 RED RETROSPOT PAPER NAPKINS ',
  'SET6 RED SPOTTY PAPER CUPS',
  'BLACK RECORD COVER FRAME',
  'PACK OF 72 SKULL CAKE CASES',
  'SET4 SKULL BADGES',
  'BLUE POLKADOT CUP',
  'FANCY FONT BIRTHDAY CARD, ',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'BIG DOUGHNUT FRIDGE MAGNETS',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'UNION JACK FLAG PASSPORT COVER ',
  'PINK UNION JACK  PASSPORT COVER ',
  'STARS GIFT TAPE ',
  'PACK OF 60 MUSHROOM CAKE CASES',
  'PACK OF 6 SKULL PAPER CUPS',
  'SPACEBOY BIRTHDAY CARD',
  'RECORD FRAME 7 SINGLE SIZE ',
  'SNOWSTORM PHOTO FRAME FRIDGE MAGNET',
  'SMALL POPCORN HOLDER',
  'LARGE POPCORN HOLDER ',
  'COFFEE MUG PEARS  DESIGN',
  'COFFEE MUG APPLES DESIGN',
  'OFFICE MUG WARMER POLKADOT',
  'OFFICE MUG WARMER CHOCBLUE',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'CHARLOTTE BAG PINK POLKADOT',
  'DOORMAT RESPECTABLE HOUSE',
  'METAL SIGN TAKE IT OR LEAVE IT ',
  'CABIN BAG VINTAGE RETROSPOT',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PLASTERS IN TIN STRONGMAN',
  'PLASTERS IN TIN CIRCUS PARADE ',
  'TRAVEL SEWING KIT',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'SET OF 2 TEA TOWELS APPLE AND PEARS',
  'JAM MAKING SET PRINTED',
  'GINGERBREAD MAN COOKIE CUTTER',
  'LONDON BUS COFFEE MUG',
  'CHILDRENS CIRCUS PARADE MUG',
  'CIRCUS PARADE CHILDRENS EGG CUP ',
  'DOORMAT UNION FLAG',
  'NO SINGING METAL SIGN',
  'PINK 3 PIECE POLKADOT CUTLERY SET'],
 ['CLOTHES PEGS RETROSPOT PACK 24 ',
  'BAKING MOULD EASTER EGG MILK CHOC',
  'BAKING MOULD EASTER EGG WHITE CHOC'],
 ['CAKE PLATE LOVEBIRD WHITE',
  'CAKE PLATE LOVEBIRD PINK',
  'METAL SIGN,CUPCAKE SINGLE HOOK',
  'METAL SIGN CUPCAKE SINGLE HOOK'],
 ['RED RETROSPOT CAKE STAND'],
 ['RED RETROSPOT CAKE STAND'],
 ['RED RETROSPOT CHILDRENS UMBRELLA',
  'DOLLY MIXTURE CHILDRENS UMBRELLA',
  '12 PENCIL SMALL TUBE WOODLAND',
  '12 PENCILS SMALL TUBE RED RETROSPOT',
  'BOOM BOX SPEAKER BOYS',
  'SET6 RED SPOTTY PAPER CUPS',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'SET4 SKULL BADGES',
  'RED RETROSPOT CUP',
  'SKULLS  WATER TRANSFER TATTOOS ',
  'FOLDING UMBRELLA REDWHITE POLKADOT',
  'FOLDING UMBRELLA CREAM POLKADOT',
  'POLKADOT RAIN HAT ',
  'CUTE CATS TAPE',
  'PACK OF 20 SKULL PAPER NAPKINS',
  'TEA PARTY BIRTHDAY CARD',
  'ROBOT BIRTHDAY CARD',
  'OFFICE MUG WARMER PINK',
  'OFFICE MUG WARMER CHOCBLUE',
  'TEA BAG PLATE RED RETROSPOT',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'DOORMAT RESPECTABLE HOUSE',
  'GUMBALL COAT RACK',
  'CABIN BAG VINTAGE RETROSPOT',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PLASTERS IN TIN CIRCUS PARADE ',
  '4 TRADITIONAL SPINNING TOPS',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'TABLECLOTH RED APPLES DESIGN ',
  'SET OF 2 TEA TOWELS APPLE AND PEARS',
  'CALENDAR PAPER CUT DESIGN',
  'JAM MAKING SET PRINTED',
  'GINGERBREAD MAN COOKIE CUTTER'],
 ['INFLATABLE POLITICAL GLOBE ',
  'EDWARDIAN PARASOL RED',
  'ASSORTED COLOUR MINI CASES',
  'RED RETROSPOT MINI CASES',
  'BLUE ROSE FABRIC MIRROR',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'VINTAGE HEADS AND TAILS CARD GAME ',
  'RED  HARMONICA IN BOX ',
  'PACK OF 60 MUSHROOM CAKE CASES',
  'PACK OF 60 PINK PAISLEY CAKE CASES',
  'TEA PARTY BIRTHDAY CARD',
  'PINK DOUGHNUT TRINKET POT ',
  'PAPER BUNTING RETROSPOT',
  'COFFEE MUG PEARS  DESIGN',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'ROUND SNACK BOXES SET OF 4 FRUITS ',
  'WOODLAND PARTY BAG  STICKER SET',
  'RETROSPOT PARTY BAG  STICKER SET',
  'LUNCH BOX WITH CUTLERY RETROSPOT ',
  'REGENCY CAKESTAND 3 TIER',
  'SET OF 9 HEART SHAPED BALLOONS',
  'SILK PURSE BABUSHKA RED',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PLASTERS IN TIN CIRCUS PARADE ',
  'CLOTHES PEGS RETROSPOT PACK 24 ',
  'EASTER TIN BUNNY BOUQUET',
  'TEA FOR ONE POLKADOT',
  'SET OF 2 TEA TOWELS APPLE AND PEARS',
  'CALENDAR PAPER CUT DESIGN',
  'ASSORTED BOTTLE TOP  MAGNETS ',
  'JAM MAKING SET PRINTED',
  'JAM JAR WITH PINK LID',
  'GINGERBREAD MAN COOKIE CUTTER',
  'CIRCUS PARADE CHILDRENS EGG CUP ',
  'EDWARDIAN PARASOL BLACK',
  'EDWARDIAN PARASOL NATURAL',
  'EDWARDIAN PARASOL PINK',
  'CHERRY BLOSSOM  DECORATIVE FLASK'],
 ['MINI FUNKY DESIGN TAPES',
  'LUNCH BAG RED RETROSPOT',
  'NURSES BAG SOFT TOY',
  'TOOL BOX SOFT TOY ',
  'DOCTORS BAG SOFT TOY',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'SET 12 KIDS  WHITE CHALK STICKS',
  'SET 12 KIDS COLOUR  CHALK STICKS',
  'PACK OF 60 DINOSAUR CAKE CASES',
  'PACK OF 12 RED RETROSPOT TISSUES ',
  'WOOD STAMP SET HAPPY BIRTHDAY',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN VINTAGE PAISLEY ',
  'WOODEN CROQUET GARDEN SET',
  'WOODEN SKITTLES GARDEN SET',
  'PIGGY BANK RETROSPOT ',
  'CERAMIC CHERRY CAKE MONEY BANK',
  'CERAMIC HEART FAIRY CAKE MONEY BANK',
  'CERAMIC PIRATE CHEST MONEY BANK',
  '60 CAKE CASES DOLLY GIRL DESIGN',
  'ROMANTIC IMAGES GIFT WRAP SET'],
 ['EDWARDIAN PARASOL RED',
  'RED RETROSPOT CHARLOTTE BAG',
  'RED RETROSPOT MINI CASES',
  'RED RETROSPOT SHOPPING BAG',
  'TOOL BOX SOFT TOY ',
  'SET20 RED RETROSPOT PAPER NAPKINS ',
  'SET6 RED SPOTTY PAPER CUPS',
  'SET6 RED SPOTTY PAPER PLATES',
  'BALLOONS  WRITING SET ',
  'STARS GIFT TAPE ',
  'RED RETROSPOT PICNIC BAG',
  'BAKING SET 9 PIECE RETROSPOT ',
  'FELTCRAFT DOLL MOLLY',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'CHARLOTTE BAG PINK POLKADOT',
  '10 COLOUR SPACEBOY PEN',
  'CABIN BAG VINTAGE RETROSPOT',
  'BAKING SET SPACEBOY DESIGN',
  'CHILDS BREAKFAST SET SPACEBOY ',
  'POPPYS PLAYHOUSE KITCHEN',
  'FELTCRAFT PRINCESS LOLA DOLL',
  'BLACKBLUE POLKADOT UMBRELLA',
  'JUMBO BAG RED RETROSPOT'],
 ['WOODLAND CHARLOTTE BAG',
  'RED RETROSPOT MINI CASES',
  'RED RETROSPOT APRON ',
  'SET20 RED RETROSPOT PAPER NAPKINS ',
  'SET6 RED SPOTTY PAPER CUPS',
  'SET6 RED SPOTTY PAPER PLATES',
  'SET10 RED POLKADOT PARTY CANDLES',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'STARS GIFT TAPE ',
  'ROUND SNACK BOXES SET OF4 WOODLAND ',
  'WOODLAND PARTY BAG  STICKER SET',
  'RETROSPOT PARTY BAG  STICKER SET',
  'CHILDRENS APRON SPACEBOY DESIGN',
  'PAPERWEIGHT CHILDHOOD MEMORIES',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN STRONGMAN',
  'PLASTERS IN TIN CIRCUS PARADE ',
  'ALARM CLOCK BAKELIKE GREEN',
  'ALARM CLOCK BAKELIKE RED ',
  'ALARM CLOCK BAKELIKE PINK',
  'ALARM CLOCK BAKELIKE ORANGE'],
 ['RED RETROSPOT MINI CASES',
  'NURSES BAG SOFT TOY',
  'WOODLAND DESIGN  COTTON TOTE BAG',
  'RED RETROSPOT CAKE STAND',
  'TEA PARTY BIRTHDAY CARD',
  'PAPER BUNTING RETROSPOT',
  'BAKING SET 9 PIECE RETROSPOT ',
  'RETROSPOT TEA SET CERAMIC 11 PC ',
  'SILK PURSE BABUSHKA PINK',
  'GUMBALL COAT RACK',
  'PLASTERS IN TIN CIRCUS PARADE ',
  'WOODEN SKITTLES GARDEN SET',
  'SET OF 20 KIDS COOKIE CUTTERS',
  'CREAM FELT EASTER EGG BASKET'],
 ['SET2 RED RETROSPOT TEA TOWELS ',
  'SET20 RED RETROSPOT PAPER NAPKINS ',
  'RED POLKADOT COFFEE  MUG',
  'CUTE CATS TAPE',
  'STARS GIFT TAPE ',
  'BAKING SET 9 PIECE RETROSPOT ',
  'SET OF SALT AND PEPPER TOADSTOOLS',
  'EDWARDIAN PARASOL BLACK',
  'RETRO PLASTIC POLKA TRAY'],
 ['KITTY PENCIL ERASERS',
  'SLEEPING CAT ERASERS',
  'PARTY TIME PENCIL ERASERS',
  'RED RETROSPOT MINI CASES',
  'SET3 BOOK BOX GREEN GINGHAM FLOWER ',
  'RED GINGHAM ROSE JEWELLERY BOX',
  'SET3 RED GINGHAM ROSE STORAGE BOX',
  'STRAWBERRY LUNCH BOX WITH CUTLERY',
  'DINOSAUR LUNCH BOX WITH CUTLERY',
  'BUTTERFLIES STICKERS',
  'RED TOADSTOOL LED NIGHT LIGHT',
  'HOME SWEET HOME MUG',
  'BAKING SET 9 PIECE RETROSPOT ',
  'RETROSPOT TEA SET CERAMIC 11 PC ',
  'JUMBO BAG SPACEBOY DESIGN',
  'REGENCY CAKESTAND 3 TIER',
  'WATERING CAN PINK BUNNY',
  'FAIRY TALE COTTAGE NIGHTLIGHT',
  'GUMBALL COAT RACK',
  'PLASTERS IN TIN SPACEBOY',
  'PLASTERS IN TIN SKULLS',
  'PLASTERS IN TIN WOODLAND ANIMALS',
  'PLASTERS IN TIN STRONGMAN',
  'PLASTERS IN TIN CIRCUS PARADE ',
  'BAKING SET SPACEBOY DESIGN',
  'SPACEBOY LUNCH BOX ',
  'CIRCUS PARADE LUNCH BOX ',
  'CHARLOTTE BAG DOLLY GIRL DESIGN',
  'RED BABY BUNTING ',
  'ALARM CLOCK BAKELIKE CHOCOLATE',

In [23]:
print(transactions[0])

['INFLATABLE POLITICAL GLOBE ', 'SET2 RED RETROSPOT TEA TOWELS ', 'PANDA AND BUNNIES STICKER SHEET', 'RED TOADSTOOL LED NIGHT LIGHT', 'VINTAGE HEADS AND TAILS CARD GAME ', 'STARS GIFT TAPE ', 'VINTAGE SEASIDE JIGSAW PUZZLES', 'ROUND SNACK BOXES SET OF4 WOODLAND ', 'MINI PAINT SET VINTAGE ', 'MINI JIGSAW CIRCUS PARADE ', 'MINI JIGSAW SPACEBOY', 'SPACEBOY LUNCH BOX ', 'CIRCUS PARADE LUNCH BOX ', 'LUNCH BOX I LOVE LONDON', 'CHARLOTTE BAG DOLLY GIRL DESIGN', 'ALARM CLOCK BAKELIKE GREEN', 'ALARM CLOCK BAKELIKE RED ', 'ALARM CLOCK BAKELIKE PINK', 'SET 2 TEA TOWELS I LOVE LONDON ']

In [25]:
encoder = TransactionEncoder()
encoded_transactions = encoder.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(encoded_transactions, columns= encoder.columns_)
df_encoded

,50S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR TLIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC TLIGHT HOLDER STAR LARGE,ZINC TLIGHT HOLDER STARS SMALL
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
437,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [27]:
frequent_itemsets = apriori(df_encoded, use_colnames= True, min_support= 0.01)
frequent_itemsets

       support                                           itemsets
0     0.020408                               ( DOLLY GIRL BEAKER)
1     0.011338                     ( I LOVE LONDON MINI BACKPACK)
2     0.013605                 ( SET 2 TEA TOWELS I LOVE LONDON )
3     0.036281                          ( SPACEBOY BABY GIFT SET)
4     0.027211                           (10 COLOUR SPACEBOY PEN)
...        ...                                                ...
8335  0.011338  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
8336  0.011338  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
8337  0.011338  (SET6 RED SPOTTY PAPER PLATES, SET OF 9 HEART ...
8338  0.011338  (SET6 RED SPOTTY PAPER PLATES, PLASTERS IN TIN...
8339  0.011338  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...

[8340 rows x 2 columns]

In [29]:
print(len(frequent_itemsets))

8340

In [31]:
print(frequent_itemsets.head())

    support                            itemsets
0  0.020408                ( DOLLY GIRL BEAKER)
1  0.011338      ( I LOVE LONDON MINI BACKPACK)
2  0.013605  ( SET 2 TEA TOWELS I LOVE LONDON )
3  0.036281           ( SPACEBOY BABY GIFT SET)
4  0.027211            (10 COLOUR SPACEBOY PEN)

In [33]:
rules = association_rules(frequent_itemsets, metric = "support", min_threshold = 0.01)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(CHARLOTTE BAG DOLLY GIRL DESIGN),( DOLLY GIRL BEAKER),0.058957,0.020408,0.011338,0.192308,9.423077,1.0,0.010135,1.212828,0.949880,0.166667,0.175481,0.373932
1,( DOLLY GIRL BEAKER),(CHARLOTTE BAG DOLLY GIRL DESIGN),0.020408,0.058957,0.011338,0.555556,9.423077,1.0,0.010135,2.117347,0.912500,0.166667,0.527711,0.373932
2,(DOLLY GIRL CHILDRENS BOWL),( DOLLY GIRL BEAKER),0.040816,0.020408,0.015873,0.388889,19.055556,1.0,0.015040,1.602968,0.987842,0.350000,0.376157,0.583333
3,( DOLLY GIRL BEAKER),(DOLLY GIRL CHILDRENS BOWL),0.020408,0.040816,0.015873,0.777778,19.055556,1.0,0.015040,4.316327,0.967262,0.350000,0.768322,0.583333
4,(DOLLY GIRL CHILDRENS CUP),( DOLLY GIRL BEAKER),0.036281,0.020408,0.013605,0.375000,18.375000,1.0,0.012865,1.567347,0.981176,0.315789,0.361979,0.520833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85217,(SET6 RED SPOTTY PAPER CUPS),"(PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...",0.122449,0.011338,0.011338,0.092593,8.166667,1.0,0.009950,1.089546,1.000000,0.092593,0.082187,0.546296
85218,(SET OF 9 BLACK SKULL BALLOONS),"(PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...",0.058957,0.013605,0.011338,0.192308,14.134615,1.0,0.010536,1.221250,0.987470,0.185185,0.181167,0.512821
85219,(PACK OF 6 SKULL PAPER CUPS),"(PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...",0.056689,0.011338,0.011338,0.200000,17.640000,1.0,0.010695,1.235828,1.000000,0.200000,0.190826,0.600000
85220,(SET20 RED RETROSPOT PAPER NAPKINS ),"(PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...",0.117914,0.011338,0.011338,0.096154,8.480769,1.0,0.010001,1.093839,1.000000,0.096154,0.085789,0.548077
85221,(PACK OF 6 SKULL PAPER PLATES),"(PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...",0.049887,0.011338,0.011338,0.227273,20.045455,1.0,0.010772,1.279445,1.000000,0.227273,0.218411,0.613636

In [35]:
print(rules)

                                antecedents  \
0         (CHARLOTTE BAG DOLLY GIRL DESIGN)
1                      ( DOLLY GIRL BEAKER)
2               (DOLLY GIRL CHILDRENS BOWL)
3                      ( DOLLY GIRL BEAKER)
4                (DOLLY GIRL CHILDRENS CUP)
...                                     ...
85217          (SET6 RED SPOTTY PAPER CUPS)
85218       (SET OF 9 BLACK SKULL BALLOONS)
85219          (PACK OF 6 SKULL PAPER CUPS)
85220  (SET20 RED RETROSPOT PAPER NAPKINS )
85221        (PACK OF 6 SKULL PAPER PLATES)

                                             consequents  antecedent support  \
0                                   ( DOLLY GIRL BEAKER)            0.058957
1                      (CHARLOTTE BAG DOLLY GIRL DESIGN)            0.020408
2                                   ( DOLLY GIRL BEAKER)            0.040816
3                            (DOLLY GIRL CHILDRENS BOWL)            0.020408
4                                   ( DOLLY GIRL BEAKER)            0.036281
...                                                  ...                 ...
85217  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...            0.122449
85218  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...            0.058957
85219  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...            0.056689
85220  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...            0.117914
85221  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...            0.049887

       consequent support   support  confidence       lift  representativity  \
0                0.020408  0.011338    0.192308   9.423077               1.0
1                0.058957  0.011338    0.555556   9.423077               1.0
2                0.020408  0.015873    0.388889  19.055556               1.0
3                0.040816  0.015873    0.777778  19.055556               1.0
4                0.020408  0.013605    0.375000  18.375000               1.0
...                   ...       ...         ...        ...               ...
85217            0.011338  0.011338    0.092593   8.166667               1.0
85218            0.013605  0.011338    0.192308  14.134615               1.0
85219            0.011338  0.011338    0.200000  17.640000               1.0
85220            0.011338  0.011338    0.096154   8.480769               1.0
85221            0.011338  0.011338    0.227273  20.045455               1.0

       leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
0      0.010135    1.212828       0.949880  0.166667   0.175481    0.373932
1      0.010135    2.117347       0.912500  0.166667   0.527711    0.373932
2      0.015040    1.602968       0.987842  0.350000   0.376157    0.583333
3      0.015040    4.316327       0.967262  0.350000   0.768322    0.583333
4      0.012865    1.567347       0.981176  0.315789   0.361979    0.520833
...         ...         ...            ...       ...        ...         ...
85217  0.009950    1.089546       1.000000  0.092593   0.082187    0.546296
85218  0.010536    1.221250       0.987470  0.185185   0.181167    0.512821
85219  0.010695    1.235828       1.000000  0.200000   0.190826    0.600000
85220  0.010001    1.093839       1.000000  0.096154   0.085789    0.548077
85221  0.010772    1.279445       1.000000  0.227273   0.218411    0.613636

[85222 rows x 14 columns]

In [37]:
print(rules.columns)

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='object')

In [39]:
print(rules[['antecedents', 'consequents']])

                                antecedents  \
0         (CHARLOTTE BAG DOLLY GIRL DESIGN)
1                      ( DOLLY GIRL BEAKER)
2               (DOLLY GIRL CHILDRENS BOWL)
3                      ( DOLLY GIRL BEAKER)
4                (DOLLY GIRL CHILDRENS CUP)
...                                     ...
85217          (SET6 RED SPOTTY PAPER CUPS)
85218       (SET OF 9 BLACK SKULL BALLOONS)
85219          (PACK OF 6 SKULL PAPER CUPS)
85220  (SET20 RED RETROSPOT PAPER NAPKINS )
85221        (PACK OF 6 SKULL PAPER PLATES)

                                             consequents
0                                   ( DOLLY GIRL BEAKER)
1                      (CHARLOTTE BAG DOLLY GIRL DESIGN)
2                                   ( DOLLY GIRL BEAKER)
3                            (DOLLY GIRL CHILDRENS BOWL)
4                                   ( DOLLY GIRL BEAKER)
...                                                  ...
85217  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
85218  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
85219  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
85220  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...
85221  (PACK OF 20 SKULL PAPER NAPKINS, SET6 RED SPOT...

[85222 rows x 2 columns]

In [41]:
ordinal_mapping = {
    "OrderPriority": ["Medium", "High"],
    "CustomerOrderSatisfaction": [ "Very Dissatisfied", "Dissatisfied", "Prefer not to answer",
        "Satisfied", "Very Satisfied" ]}

In [43]:
encoder2 = OrdinalEncoder(categories=[
    ordinal_mapping["OrderPriority"],
    ordinal_mapping["CustomerOrderSatisfaction"]
])
df[["OrderPriority", "CustomerOrderSatisfaction"]] = encoder2.fit_transform(
    df[["OrderPriority", "CustomerOrderSatisfaction"]])

In [45]:
df2 = pd.get_dummies(df, columns=["Country", "PaymentMethod"])
basket = df2.groupby(['OrderID', 'ProductName'])['Quantity'].sum().unstack().fillna(0)
basket = basket.map(lambda x: 1 if x > 0 else 0)
basket

ProductName,50S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR TLIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC TLIGHT HOLDER STAR LARGE,ZINC TLIGHT HOLDER STARS SMALL
OrderID,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581171,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581279,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581316,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
freq = apriori(basket, min_support=0.01, use_colnames=True)
rulesmba = association_rules(freq, metric="lift", min_threshold=0.5)

/opt/anaconda3/lib/python3.12/site-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [49]:
top_rules = rulesmba.sort_values(by=['confidence', 'lift', 'support'], ascending=False).head(3)
top_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4800,(SMALL MARSHMALLOWS PINK BOWL),(SMALL DOLLY MIX DESIGN ORANGE BOWL),0.011338,0.011338,0.011338,1.0,88.2,1.0,0.011209,inf,1.0,1.0,1.0,1.0
4801,(SMALL DOLLY MIX DESIGN ORANGE BOWL),(SMALL MARSHMALLOWS PINK BOWL),0.011338,0.011338,0.011338,1.0,88.2,1.0,0.011209,inf,1.0,1.0,1.0,1.0
53691,"(CHARLOTTE BAG DOLLY GIRL DESIGN, PLASTERS IN ...","(PLASTERS IN TIN SPACEBOY, ALARM CLOCK BAKELIK...",0.011338,0.011338,0.011338,1.0,88.2,1.0,0.011209,inf,1.0,1.0,1.0,1.0

In [51]:
basket.to_csv("transactional_megastore_dataset.csv")
df2.to_csv("Cleaned_Megastore_Data.csv", index=False)

In [53]:
onehot = encoder.transform(transactions)
onehot = pd.DataFrame(onehot, columns = encoder.columns_)
onehot

,50S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR TLIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC TLIGHT HOLDER STAR LARGE,ZINC TLIGHT HOLDER STARS SMALL
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
437,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
438,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
439,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
440,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [55]:
print(onehot.mean())

 50S CHRISTMAS GIFT BAG LARGE       0.002268
 DOLLY GIRL BEAKER                  0.020408
 I LOVE LONDON MINI BACKPACK        0.011338
 NINE DRAWER OFFICE TIDY            0.002268
 SET 2 TEA TOWELS I LOVE LONDON     0.013605
                                      ...
ZINC FOLKART SLEIGH BELLS           0.018141
ZINC HERB GARDEN CONTAINER          0.002268
ZINC METAL HEART DECORATION         0.009070
ZINC TLIGHT HOLDER STAR LARGE       0.002268
ZINC TLIGHT HOLDER STARS SMALL      0.004535
Length: 1562, dtype: float64

In [57]:
bag_headers = [i for i in onehot.columns if i.lower().find('bag')>=0]
dolly_headers = [i for i in onehot.columns if i.lower().find('dolly')>=0]
bags = onehot[bag_headers]
dollys = onehot[dolly_headers]
print(bags)

      50S CHRISTMAS GIFT BAG LARGE  AIRLINE BAG VINTAGE JET SET BROWN  \
0                            False                              False
1                            False                              False
2                            False                              False
3                            False                              False
4                            False                              False
..                             ...                                ...
436                          False                              False
437                          False                              False
438                          False                              False
439                          False                              False
440                          False                              False

     AIRLINE BAG VINTAGE JET SET RED  AIRLINE BAG VINTAGE JET SET WHITE  \
0                              False                              False
1                              False                              False
2                              False                              False
3                              False                              False
4                              False                              False
..                               ...                                ...
436                            False                              False
437                            False                              False
438                            False                              False
439                            False                              False
440                            False                              False

     AIRLINE BAG VINTAGE TOKYO 78  AIRLINE BAG VINTAGE WORLD CHAMPION   \
0                           False                                False
1                           False                                False
2                           False                                False
3                           False                                False
4                           False                                False
..                            ...                                  ...
436                         False                                False
437                         False                                False
438                         False                                False
439                         False                                False
440                         False                                False

     BAG 125g SWIRLY MARBLES  BAG 250g SWIRLY MARBLES  BLUE PARTY BAGS   \
0                      False                    False             False
1                      False                    False             False
2                      False                    False             False
3                      False                    False             False
4                      False                    False             False
..                       ...                      ...               ...
436                    False                    False             False
437                    False                    False             False
438                    False                    False             False
439                    False                    False             False
440                    False                    False             False

     BLUE POLKADOT KIDS BAG  ...  STRAWBERRY SHOPPER BAG  SUKI  SHOULDER BAG  \
0                     False  ...                   False               False
1                     False  ...                   False               False
2                     False  ...                   False               False
3                     False  ...                   False               False
4                     False  ...                   False               False
..                      ...  ...                     ...                 ...
436                   False  ...                   False               False
437                   False  ...                   False               False
438                   False  ...                   False               False
439                   False  ...                   False               False
440                   False  ...                   False               False

     SWIRLY CIRCULAR RUBBERS IN BAG  TEA BAG PLATE RED RETROSPOT  \
0                             False                        False
1                             False                        False
2                             False                        False
3                             False                        False
4                             False                         True
..                              ...                          ...
436                           False                        False
437                           False                        False
438                           False                        False
439                           False                        False
440                           False                        False

     TOTE BAG I LOVE LONDON  VINTAGE CHRISTMAS PAPER GIFT BAG  \
0                     False                             False
1                     False                             False
2                     False                             False
3                     False                             False
4                     False                             False
..                      ...                               ...
436                   False                             False
437                   False                             False
438                   False                             False
439                   False                             False
440                   False                             False

     VINTAGE DOILY JUMBO BAG RED   WOODLAND CHARLOTTE BAG  \
0                           False                   False
1                           False                   False
2                           False                   False
3                           False                   False
4                           False                    True
..                            ...                     ...
436                         False                   False
437                         False                   False
438                         False                   False
439                         False                   False
440                         False                   False

     WOODLAND DESIGN  COTTON TOTE BAG  WOODLAND PARTY BAG  STICKER SET
0                               False                            False
1                               False                            False
2                               False                            False
3                               False                            False
4                               False                            False
..                                ...                              ...
436                             False                            False
437                             False                            False
438                             False                            False
439                             False                            False
440                             False                            False

[441 rows x 94 columns]

In [59]:
bags = (bags.sum(axis=1) > 0.0).values
dollys = (dollys.sum(axis=1) > 0.0).values
print(bags)

[ True  True  True  True  True  True False False  True False  True  True
  True  True  True  True False  True False  True  True False False False
 False  True  True  True  True  True  True False  True False False False
  True False False False  True  True  True  True False  True  True False
 False False  True False False False False False  True  True False False
  True  True  True  True False  True False False False  True  True  True
 False False False False False False False False False False  True False
  True False  True False False  True False False  True False  True False
  True False False  True  True False  True False False False  True  True
 False  True  True False  True False False False  True  True False  True
  True  True False  True False  True False False False  True  True False
 False False  True  True  True False False False  True  True  True  True
 False  True False False False  True  True  True False  True  True  True
 False  True False  True  True False  True  True  True False  True  True
 False  True  True False  True  True  True  True  True  True False  True
 False  True  True False  True  True False  True  True False  True False
  True  True False  True  True False False  True  True False False  True
 False  True  True False  True  True  True False False False False  True
 False  True False False False  True False False  True False False False
  True False  True  True False  True  True  True False  True False  True
 False  True False  True  True  True False False  True False  True  True
 False False False  True  True  True  True  True False False False  True
  True  True  True  True  True False  True False False False  True  True
 False False False  True  True  True False  True  True  True False False
 False  True False  True  True  True  True False False False False  True
  True False False  True  True False False  True  True False  True False
 False False False False False False False  True  True False  True False
 False False  True  True  True False  True False False False False  True
  True False  True False False  True False False False  True False  True
  True False  True  True False False  True  True False False  True False
  True False  True  True  True False  True False  True False  True False
 False False False  True  True  True False  True  True  True  True False
  True False  True False False  True  True  True  True  True  True  True
 False  True  True  True  True False False False  True  True  True False
 False False False False False False False  True False False False  True
  True  True  True  True False  True  True False  True  True  True False
 False  True False  True False False False False False]

In [61]:
aggregated = pd.DataFrame(np.vstack([bags, dollys]).T, columns = ['bags', 'dolly'])
print(aggregated.head())

   bags  dolly
0  True   True
1  True   True
2  True  False
3  True   True
4  True  False

In [63]:
print(aggregated.mean())

bags     0.517007
dolly    0.333333
dtype: float64